In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [3]:
pd.__version__

'2.3.1'

In [4]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [6]:
df.shape

(9704, 11)

In [7]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [8]:
df.groupby('fuel_type').count()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
fuel_type                                                                   
Diesel                    4806           4601        4461            4806   
Gasoline                  4898           4621        4535            4898   

           acceleration  model_year  origin  drivetrain  num_doors  \
fuel_type                                                            
Diesel             4350        4806    4806        4806       4550   
Gasoline           4424        4898    4898        4898       4652   

           fuel_efficiency_mpg  
fuel_type                       
Diesel                    4806  
Gasoline                  4898

In [9]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [10]:
df['fuel_type'].nunique()

2

In [11]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [12]:
df['origin'].nunique()

3

In [13]:
df['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [14]:
df[df['origin']=='Asia'].max()

engine_displacement                  370
num_cylinders                       11.0
horsepower                         245.0
vehicle_weight               4661.144932
acceleration                        22.7
model_year                          2023
origin                              Asia
fuel_type                       Gasoline
drivetrain             Front-wheel drive
num_doors                            4.0
fuel_efficiency_mpg            23.759123
dtype: object

In [15]:
df['horsepower'].describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [16]:
df['horsepower'].median()

np.float64(149.0)

In [17]:
df['horsepower'].unique()

array([159.,  97.,  78.,  nan, 140., 127., 239., 174., 123., 100., 145.,
       193., 160., 179., 180., 132., 110., 126., 197., 133., 144., 156.,
       157., 206., 154., 153., 136., 168., 149., 143., 158., 176., 108.,
       125., 142., 139., 170., 135., 202.,  99., 152., 148., 151., 155.,
       146., 199., 128., 103., 182., 141., 113., 109., 196., 111., 118.,
       222., 122., 194., 166., 101.,  72., 232., 172., 165., 177., 190.,
       129., 184., 147., 137., 163., 162., 186., 104., 120., 200., 189.,
       167., 164., 191., 195.,  96., 181.,  71., 130., 150., 192., 217.,
       112., 220., 185.,  83., 124., 161., 169.,  98., 117., 134.,  80.,
        92., 115., 121., 214.,  94.,  90., 210., 138., 198., 175., 183.,
       187., 173.,  95., 131., 106., 204.,  93., 114., 178., 207., 171.,
       188., 230.,  87., 227., 119., 105., 102.,  73., 208., 116.,  79.,
        91., 209.,  68., 237.,  89.,  82.,  77., 213.,  59., 216., 201.,
        66.,  88.,  53., 205., 223.,  86.,  43., 10

In [18]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [19]:
df['horsepower'] = df['horsepower'].fillna(152)

In [20]:
df['horsepower'].describe()

count    9704.000000
mean      149.828215
std        28.775248
min        37.000000
25%       131.000000
50%       152.000000
75%       168.000000
max       271.000000
Name: horsepower, dtype: float64

In [21]:
df['horsepower'].median()

np.float64(152.0)

In [23]:
df.shape

(9704, 11)

In [24]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [37]:
df_asia = df.loc[df['origin']=='Asia',['vehicle_weight','model_year']]

In [40]:
df_asia = df_asia.reset_index(drop=True)
df_asia

vehicle_weight  model_year
0        2714.219310        2016
1        2783.868974        2010
2        3582.687368        2007
3        2231.808142        2011
4        2659.431451        2016
...              ...         ...
3242     3948.404625        2018
3243     3680.341381        2016
3244     2545.070139        2012
3245     3107.427820        2005
3246     2908.043477        2005

[3247 rows x 2 columns]

In [78]:
X = df_asia.iloc[0:7]

In [79]:
X

vehicle_weight  model_year
0     2714.219310        2016
1     2783.868974        2010
2     3582.687368        2007
3     2231.808142        2011
4     2659.431451        2016
5     2844.227534        2014
6     3761.994038        2019

In [80]:
X = X.values

In [81]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [82]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [83]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [84]:
XTX = X.T.dot(X)

In [85]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [86]:
XTX_inv = np.linalg.inv(XTX)

In [87]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [88]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [89]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [96]:
w_int = XTX_inv.dot(X.T)
w_int

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [98]:
w = w_int.dot(y)

In [101]:
w

array([0.01386421, 0.5049067 ])

In [102]:
w.sum()

np.float64(0.5187709081074016)